apiVersion: v1
kind: Service
metadata:
  name: kubernetes-cd-pipeline-service
spec:
  selector:
    app: kubernetes-cd-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
