name: continuous deployment

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: your-dockerhub-username/kubernetes-cd-pipeline
  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}, ${{ env.DOCKER_IMAGE }}:latest

      - name: set up kubectl
        uses: azure/setup-kubectl@v1

      - name: deploy to kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=./kubeconfig
          kubectl set image deployment/kubernetes-cd-pipeline kubernetes-cd-pipeline=${{ env.DOCKER_IMAGE }}:${{ github.sha }} -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/kubernetes-cd-pipeline -n ${{ env.K8S_NAMESPACE }}
